
export default new Map([
["src/content/parts/neural-networks/02-your-alphabet.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F02-your-alphabet.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/01-the-problem.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F01-the-problem.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/03-into-numbers.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F03-into-numbers.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/05-how-wrong.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F05-how-wrong.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/04-the-network.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F04-the-network.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/07-the-whole-loop.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F07-the-whole-loop.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/08-read-my-writing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F08-read-my-writing.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/06-learning.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F06-learning.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/09-break-it.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F09-break-it.mdx&astroContentModuleFlag=true")],
["src/content/parts/neural-networks/10-more-layers.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fparts%2Fneural-networks%2F10-more-layers.mdx&astroContentModuleFlag=true")]]);
		